### ISSUE TITLE
Assertion failure in calcstepsizes

### ISSUE THREAD

**Issue by asarubbo** [mdadams/jasper#57] opened 2016-10-24 13:43 UTC
On 1.900.13:

```
imginfo: /tmp/portage/media-libs/jasper-1.900.13/work/jasper-1.900.13/src/libjasper/jpc/jpc_dec.c:1637: void calcstepsizes(uint_fast16_t, int, uint_fast16_t *): Assertion `!((expn + (numrlvls - 1) - (numrlvls - 1 - ((bandno > 0) ? ((bandno + 2) / 3) : (0)))) & (~0x1f))' failed.
```

Testcase: https://github.com/asarubbo/poc/blob/master/00012-jasper-assert-calcstepsizes

**Comment by mdadams** [comment] 2016-10-28 03:29
This appears to be a duplicate of the problem fixed by commit f7038068550fba0e41e1d0c355787f1dcd5bf330.  So, this test case is now handled properly.

**Closed by mdadams** 2016-10-28 03:29 UTC
