### ISSUE TITLE
Build fails to find and link system GLUT on macOS

### ISSUE THREAD

**Issue by ilovezfs** [mdadams/jasper#100] opened 2016-12-01 13:01 UTC
macOS does not need XQuartz (i.e., X11) for GLUT support, since it already has a system GLUT framework. One problem that arises is when software assumes that the glut.h header will be in a subdirectory named "GL." On macOS this is not the case for the system GLUT framework. The glut.h just hangs out at the top level of the framework's Headers directory. However, this can get confusing because it is possible to "accidentally" find a non-system GLUT header belonging to either XQuartz or to `freeglut` both of which have header directories containing a top-level GL subdirectory, and then the glut.h in there.

The various combinations are
Command line tools installed, command line tools not installed
Xcode installed, Xcode not installed
SDKROOT set to the Xcode SDK directory, SDKROOT unset
XQuartz installed, XQuartz not installed
freeglut installed, freeglut not installed

Note that freeglut without XQuartz is possible but would be a misconfigured system since freeglut depends on XQuartz.

In order to make sure we find and link the system GLUT, I'm using the following fix:
```
    # Fix OpenGL support
    ["CMakeLists.txt", "src/appl/jiv.c"].each do |f|
      inreplace f, "GL/glut.h", "glut.h"
    end
    inreplace "src/appl/CMakeLists.txt",
      "add_executable(jiv jiv.c)",
      "add_executable(jiv jiv.c)\n\tinclude_directories(${GLUT_INCLUDE_DIR})"
```
together with
```
      glut_lib = "#{MacOS.sdk_path}/System/Library/Frameworks/GLUT.framework"
      system "cmake", "..", "-DGLUT_glut_LIBRARY=#{glut_lib}", *std_cmake_args
```

Note that without these changes, the system GLUT header will not be found, and GLUT and OpenGL will be disabled or will link the XQuartz or freeglut versions, neither of which is a particularly desirable outcome given that the system version is sitting right there.

As a patch this looks like the following: https://gist.github.com/ilovezfs/0709bba29eba2c65adde82ba50edfc06

**Comment by mdadams** [comment] 2016-12-01 13:59
@ilovezfs  I have tried to incorporate your changes in a way that will not break things for non-OSX platforms.  The result can be found in commit cf90616e29998f5345b78f770f05c03b25877d8f.  Since Travis CI's OSX builds are lagging very far behind for me these days (more than a day often), I cannot actually tell yet if this problem is fixed in the version of OSX on Travis CI.  In any case, since they might be running a different version from the one that you are running, it would be helpful to know if the problem is fixed on your OSX version.  So, please let me know if the above commit fixes things for you.

**Comment by mdadams** [comment] 2016-12-01 14:11
@ilovezfs Oops.  I did my test for OSX wrong in jiv.c.  Please use commit 4e911af31d74b08a3d3855837282c4e870efe297 instead.

**Comment by mdadams** [comment] 2016-12-01 14:52
@ilovezfs Now the build breaks for OSX on Travis CI. :(

**Comment by ilovezfs** [comment] 2016-12-01 16:47
@mdadams dies on the include:
https://gist.github.com/ilovezfs/3e7f2701d9bf7662dad09182e197ad5f

**Comment by ilovezfs** [comment] 2016-12-01 16:50
@mdadams I think you missed the
```
    inreplace "src/appl/CMakeLists.txt",
      "add_executable(jiv jiv.c)",
      "add_executable(jiv jiv.c)\n\tinclude_directories(${GLUT_INCLUDE_DIR})"
```

https://github.com/mdadams/jasper/blob/master/src/appl/CMakeLists.txt#L22-L29

**Comment by mdadams** [comment] 2016-12-01 17:01
But there is an include_directories command in the top-level CMakeLists.txt file.  My understanding is that this should apply globally.  Isn't this the case?

**Comment by mdadams** [comment] 2016-12-01 17:04
To be more specific, there is an include_directories on line 203.  See:
https://github.com/mdadams/jasper/commit/cf90616e29998f5345b78f770f05c03b25877d8f

**Comment by mdadams** [comment] 2016-12-01 17:07
@ilovezfs Incidentally, I had to back out my earlier changes, at least for now, in order to avoid breaking the Travis CI testing for OSX.

**Comment by ilovezfs** [comment] 2016-12-01 17:19
cd /tmp/jasper-20161201-48499-11kghig/build/src/appl && /usr/local/Homebrew/Library/Homebrew/shims/super/clang -I/usr/local/include -F"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/GLUT.framework/Headers /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks" -I/tmp/jasper-20161201-48499-11kghig/build/src/libjasper/include -I/tmp/jasper-20161201-48499-11kghig/src/libjasper/include -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.11 -std=gnu11 -o CMakeFiles/jiv.dir/jiv.c.o -c /tmp/jasper-20161201-48499-11kghig/src/appl/jiv.c


-F"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/GLUT.framework/Headers /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks"

looks bogus since it should be -I for the headers and -F for the frameworks

**Comment by mdadams** [comment] 2016-12-02 01:20
@ilovezfs Which version of cmake are you using?

**Comment by ilovezfs** [comment] 2016-12-02 02:36
CMake 3.7.1

**Comment by mdadams** [comment] 2016-12-02 07:18
@ilovezfs As far as I can tell, my use of CMake to test for GLUT is correct.  So, in this sense, the problem appears to be a bug in CMake (as opposed to a bug in JasPer's use of CMake).  In particular, there appears to be a bug in the CMake module that finds the GLUT library (for the OSX case).  Would you not agree with this assessment?  If this build problem is due to a CMake bug, this is unfortunate, since you have the most recent version of CMake, meaning that the bug in CMake has not been fixed in the most recent version.  (Perhaps, you could file a bug report with the CMake developers in this regard?)  Even if the fault is with CMake, I would like to try to find a workaround.  But this workaround must not break the build for other platforms (or other versions of OSX from what you have).  I am still not sure that I understand all the details of the OSX side to fix things in a reasonable way.  Also, might someone want to build with the other version of GLUT installed on OSX?  If I understood you correctly, there are potentially two.

**Comment by mdadams** [comment] 2016-12-02 07:31
@ilovezfs Concerning your snippet from above:
    inreplace "src/appl/CMakeLists.txt",
      "add_executable(jiv jiv.c)",
      "add_executable(jiv jiv.c)\n\tinclude_directories(${GLUT_INCLUDE_DIR})"
You appear to be adding the "include_directories" AFTER the jiv target is added.
My understanding of CMake is that this will not affect the jiv target unless the include_directories comes before the add_executable.  For example, see some of the comments here:
http://stackoverflow.com/questions/31969547/what-is-the-difference-between-include-directories-and-target-include-directorie

**Comment by ilovezfs** [comment] 2016-12-02 07:48
Note there is an upstream issue about GLUT (https://gitlab.kitware.com/cmake/cmake/issues/16045), which was filed by ... me ... in April: https://cmake.org/Bug/view.php?id=16045

So we're kind of on our own it seems.

The include_directories definitely affects the build. I cannot explain it yet in any satisfactory fashion since I'm no CMake expert.

Without the replacement in src/appl/CMakeLists.txt:
```
cd /tmp/jasper-20161201-71994-3y4978/jasper-version-2.0.2/build/src/appl && /usr/local/Homebrew/Library/Homebrew/shims/super/clang   -I/usr/local/include -F"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/GLUT.framework/Headers /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks" -I/tmp/jasper-20161201-71994-3y4978/jasper-version-2.0.2/build/src/libjasper/include -I/tmp/jasper-20161201-71994-3y4978/jasper-version-2.0.2/src/libjasper/include  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.11   -std=gnu11 -o CMakeFiles/jiv.dir/jiv.c.o   -c /tmp/jasper-20161201-71994-3y4978/jasper-version-2.0.2/src/appl/jiv.c
/tmp/jasper-20161201-71994-3y4978/jasper-version-2.0.2/src/appl/jiv.c:67:10: fatal error: 'glut.h'
      file not found
#include <glut.h>
```
With the replacement:
```
==> Summary
🍺  /usr/local/Cellar/jasper/2.0.2: 36 files, 469.2K, built in 9 seconds
iMac-TMP:homebrew-core joe$ brew linkage jasper
System libraries:
  /System/Library/Frameworks/GLUT.framework/Versions/A/GLUT
  /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
  /usr/lib/libSystem.B.dylib
Homebrew libraries:
  /usr/local/opt/jpeg/lib/libjpeg.8.dylib (jpeg)
Variable-referenced libraries:
  @rpath/libjasper.4.dylib
```

Same behavior with CMake 3.7.0.

Note that the bottles I shipped in https://github.com/Homebrew/homebrew-core/pull/7445 have the correct linkage:
```
iMac-TMP:homebrew-core joe$ brew install jasper
==> Downloading https://homebrew.bintray.com/bottles/jasper-2.0.2.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring jasper-2.0.2.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/jasper/2.0.2: 36 files, 469.3K
iMac-TMP:homebrew-core joe$ brew linkage jasper
System libraries:
  /System/Library/Frameworks/GLUT.framework/Versions/A/GLUT
  /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
  /usr/lib/libSystem.B.dylib
Homebrew libraries:
  /usr/local/opt/jpeg/lib/libjpeg.8.dylib (jpeg)
Variable-referenced libraries:
  @rpath/libjasper.4.dylib
```

**Comment by ilovezfs** [comment] 2016-12-02 08:27
@mdadams looks like it's a bug here: https://github.com/mdadams/jasper/blob/master/CMakeLists.txt#L203

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index abfda64..2cd6c42 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -196,13 +196,13 @@ if (JAS_ENABLE_OPENGL AND OPENGL_FOUND)
 		message("GLUT include directory: ${GLUT_INCLUDE_DIR}")
 		message("GLUT libraries: ${GLUT_LIBRARIES}")
 		set(CMAKE_REQUIRED_INCLUDES ${GLUT_INCLUDE_DIR})
-		check_include_files(GL/glut.h JAS_HAVE_GL_GLUT_H)
+		check_include_files(glut.h JAS_HAVE_GL_GLUT_H)
 		message("JAS_HAVE_GL_GLUT_H: ${JAS_HAVE_GL_GLUT_H}")
 		if (JAS_HAVE_GL_GLUT_H)
 			set(JAS_HAVE_OPENGL 1)
-			include_directories("${GLUT_INCLUDE_DIR} ${OPENGL_INCLUDE_DIR}")
+			include_directories("${GLUT_INCLUDE_DIR}" "${OPENGL_INCLUDE_DIR}/Headers")
 		else()
-			message(WARNING "The header file GL/glut.h appears to be missing.")
+			message(WARNING "The header file glut.h appears to be missing.")
 			message(WARNING "Disabling OpenGL.")
 		endif()
 	endif()
diff --git a/src/appl/jiv.c b/src/appl/jiv.c
index 15992e4..07ae66a 100644
--- a/src/appl/jiv.c
+++ b/src/appl/jiv.c
@@ -64,7 +64,7 @@
 \******************************************************************************/
 
 #include <jasper/jasper.h>
-#include <GL/glut.h>
+#include <glut.h>
 #include <stdlib.h>
 #include <math.h>
 #include <inttypes.h>
```

**Comment by mdadams** [comment] 2016-12-02 11:14
I also noticed the quoting problem in your diff above, by accident when doing some  unrelated testing on my machine.  It didn't affect things on my machine in a negative way, but it might be adversely affecting OSX.  In any case, I made a few changes that might move things closer to being fixed for your OSX system.  These changes can be found in commit ab26f6fae85ee0f4b52dcd75d7430cf47187a27c.  By any chance do these changes work for you?  Please note that I cannot simply assume that glut.h is always in the top-level include directory as opposed to the GL subdirectory, as this will break things on most/all non-OSX systems.  But I have modified the CMakeLists.txt file so that it will be happy if either glut.h or GL/glut.h is there and then jiv.c will use GL/glut.h if available and fall back on glut.h otherwise.

**Comment by ilovezfs** [comment] 2016-12-02 12:24
@mdadams That's definitely an improvement. If XQuartz is not installed, you get
```
$ brew linkage jasper
System libraries:
  /System/Library/Frameworks/GLUT.framework/Versions/A/GLUT
  /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
  /usr/lib/libSystem.B.dylib
```

However, if XQuartz is installed, you get
```
$ brew linkage jasper
System libraries:
  /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
  /opt/X11/lib/libglut.3.dylib
  /usr/lib/libSystem.B.dylib
```

And if freeglut and XQuartz are both installed, you get
```
$ brew linkage jasper
System libraries:
  /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
  /usr/lib/libSystem.B.dylib
Homebrew libraries:
  /usr/local/opt/freeglut/lib/libglut.3.dylib (homebrew/x11/freeglut)
  /usr/local/opt/jpeg/lib/libjpeg.8.dylib (jpeg)
Variable-referenced libraries:
  @rpath/libjasper.4.dylib
Possible undeclared dependencies:
  homebrew/x11/freeglut
```

I can prevent the opportunistic linkage to XQuartz or freeglut, I can hack CMake with the explicit specification I mentioned above
```
       glut_lib = "#{MacOS.sdk_path}/System/Library/Frameworks/GLUT.framework"
       system "cmake", "..", "-DGLUT_glut_LIBRARY=#{glut_lib}", *std_cmake_args
```

But presumably it would be better to just always pick the system GLUT to go with the system OpenGL, unless someone explicitly asked for XQuartz or freeglut for some special reason.

**Comment by mdadams** [comment] 2016-12-02 15:50
@ilovezfs Just to clarify:  In the various scenarios that you described above (i.e. various combinations of XQuartz and freeglut), does JasPer now build successfully, including jiv?  In other words, did I actually fix the problem on your system that either jiv is not built at all or the building of jiv fails?  If I am interpreting your comments above correctly, JasPer (without modifications) now builds successfully including jiv, except possibly that the "less desirable" version of GLUT may be used.  Is this the case?

**Comment by mdadams** [comment] 2016-12-02 15:53
@ilovezfs Incidentally, I am still waiting for the Travis CI build on OSX to complete in order to see if things work on the version of OSX on Travis CI.  I would like to ensure that things work for both your OSX environment as well as the one on Travis CI.

**Comment by mdadams** [comment] 2016-12-02 16:35
@ilovezfs With Clang under OSX on Travis CI, JasPer now builds correctly producing jiv for both the static and shared library cases.  So, things are working with GLUT on at least one OSX system now. :)
See: 
https://travis-ci.org/mdadams/jasper/jobs/180670974

**Comment by ilovezfs** [comment] 2016-12-02 16:35
@mdadams we do not permit XQuartz dependencies in Homebrew Core unless they are strictly optional. However, we deliberately install XQuartz on the CI machines in order to be able to detect cases where an XQuartz dependency is opportunistically/accidentally picked up.

So unless we're going to keep
```
glut_lib = "#{MacOS.sdk_path}/System/Library/Frameworks/GLUT.framework"
system "cmake", "..", "-DGLUT_glut_LIBRARY=#{glut_lib}", *std_cmake_args
```
in the formula for jasper *forever* (or until upstream CMake decides to do something about this, which will be in maybe 2025 or 2050 or ...), we'll need to come up with some way in your CMake setup to avoid picking up the XQuartz dependency unless the person building actually asks to use XQuartz's GLUT or freeglut.

> In other words, did I actually fix the problem on your system that either jiv is not built at all or the building of jiv fails?

Yup! All of the patching can be removed except for the need to use a CMake option that is designated advanced in FindGLUT.cmake to coerce the build system not to pick up undeclared dependencies no one asked for.

>Incidentally, I am still waiting for the Travis CI build on OSX to complete in order to see if things work on the version of OSX on Travis CI. I would like to ensure that things work for both your OSX environment as well as the one on Travis CI.

Travis CI uses Homebrew for macOS so harmonizing them should not be a problem. :)

**Comment by mdadams** [comment] 2016-12-02 16:54
On Fri, 2 Dec 2016, ilovezfs wrote:
> Yup! All of the patching can be removed except for the need to use a CMake
> option that is designated advanced in FindGLUT.cmake to coerce the build
> system not to pick up undeclared dependencies no one asked for.

@ilovezfs
I am not sure what you mean by the above.  Can you please clarify if
there is anything further that I need to change in JasPer?

Also, is it okay to mark this issue as closed now?  At least things are
now working for jiv under OSX.  As I understand it, you have a solution
that works which only involves adding an extra command line option
to cmake.  And due to my lack of expertise with OSX (and also not being a
CMake guru), I don't think that I can find any better solution than this.

Incidentally, thank you for your help along the way.  Without your
explanation about the "weird" placement of header files like glut.h under
OSX and your other comments, it would have taken me considerably longer
to resolve this issue.

**Comment by ilovezfs** [comment] 2016-12-02 17:03
>Incidentally, thank you for your help along the way. 

You're welcome. I'm sure I'll be here to bug you again :)

>Also, is it okay to mark this issue as closed now?

Sure. A plus-one of some kind from your perspective on https://gitlab.kitware.com/cmake/cmake/issues/16045 would potentially be helpful to remind CMake they actually need to get a maintainer for that module. /sigh

>As I understand it, you have a solution that works which only involves adding an extra command line option to cmake.

Yup, we can carry that extra option around indefinitely as far as I'm concerned since it doesn't involve patching your sources.

>And due to my lack of expertise with OSX (and also not being a CMake guru), I don't think that I can find any better solution than this.

That's OK!

**Comment by mdadams** [comment] 2016-12-02 18:58
On Fri, 2 Dec 2016, ilovezfs wrote:
> A plus-one of some kind from your perspective on
> https://gitlab.kitware.com/cmake/cmake/issues/16045 would potentially be
> helpful to remind CMake they actually need to get a maintainer for that
> module.

@ilovezfs
Done.  I just gave the above issue a thumb-up, which I presume is what
you meant.

> Yup, we can carry that extra option around indefinitely as far as I'm
> concerned since it doesn't involve patching your sources.

Okay, I'm glad this issue has been resolved to your satisfaction.
Hopefully, Kitware will get their act together and fix the
CMake GLUT module for OSX.

**Closed** 2016-12-02 19:00 UTC

**Comment by ilovezfs** [comment] 2016-12-02 19:01
Thanks! :white_check_mark:
