### ISSUE TITLE
Latest jasper version - version bump?

### ISSUE THREAD

**Issue by kolorafa** [mdadams/jasper#102] opened 2016-12-08 11:13 UTC
The latest version generate file with strange filename.

tag: version-1.900.31 
generates file: libjasper.so.4.0.0 (libjasper.so.4)

while (older, example):
tag: version-1.900.5 
generates file: libjasper.so.1.0.0  (libjasper.so.1)

and it breaks few programs on Antergos (Arch)

Build using:
https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/jasper

Is there a reason or is this a bug?

**Comment by anthraxx** [comment] 2016-12-08 12:20
Really? Did you hear about ABI? You will need to rebuild your stuff, thats what sonames are for. Please keep arch out of this, we have properly rebuild our packages.

**Comment by mdadams** [comment] 2016-12-08 12:42
@kolorafa You are using a shared library version of the jasper library.  Shared libraries are versioned.  The "4" in libjasper.so.4 is the version number of the library.  Whenever an incompatible change to the application binary interface (ABI) of a library occurs, the version number must be changed.  Some ABI changes have occurred for the jasper library between 1.900.1 and 2.0.5.   This is why the shared library version has changed.  The solution is to simply recompile your application program against the new shared library version, as @anthraxx has suggested.  Since this is not a bug, I am closing this issue.

**Closed by mdadams** 2016-12-08 12:42 UTC
