### ISSUE TITLE
Assertion failure in jpc_iict (another one)

### ISSUE THREAD

**Issue by asarubbo** [mdadams/jasper#55] opened 2016-10-24 10:16 UTC
On 1.900.13:

```
imginfo: /tmp/portage/media-libs/jasper-1.900.13/work/jasper-1.900.13/src/libjasper/jpc/jpc_mct.c:231: void jpc_iict(jas_matrix_t *, jas_matrix_t *, jas_matrix_t *): Assertion `((c1)->numrows_) == numrows && ((c2)->numrows_) == numrows' failed.
```

Testcase: https://github.com/asarubbo/poc/blob/master/00009-jasper-assert-jpc_iict

**Comment by mdadams** [comment] 2016-10-24 14:33
Duplicate of another one of your recent bug reports.  Fixed.  See commit dee11ec440d7908d1daf69f40a3324b27cf213ba.

**Closed by mdadams** 2016-10-24 14:33 UTC
