### ISSUE TITLE
 Abort: Assertion `qmfbid == 0x01' failed.

### ISSUE THREAD

**Issue by xiaoqx** [mdadams/jasper#142] opened 2017-06-26 03:37 UTC
An abort occurs when executing the following command:
jasper -f $FILE -t jpc -F /tmp/out.pnm -T pnm

jasper: /data/xqx/tests/libjasper-test/jasper/src/libjasper/jpc/jpc_t1cod.c:144: JPC_NOMINALGAIN: Assertion `qmfbid == 0x01' failed.
Aborted

testcase:
https://github.com/xiaoqx/pocs/blob/master/002-jasper-aborted-2

**Comment by asarubbo** [comment] 2017-08-29 10:18
duplicate of #50

**Comment by jubalh** [comment] 2019-03-12 16:03
@mdadams this one can be closed I think.

**Comment by mdadams** [comment] 2019-03-12 17:48
@jubalh  Thank you for pointing out that this issue is now fixed.  I will close it now.

**Closed by mdadams** 2019-03-12 17:48 UTC
