### ISSUE TITLE
Assertion failure in jpc_pi_nextrpcl

### ISSUE THREAD

**Issue by asarubbo** [mdadams/jasper#58] opened 2016-10-25 09:40 UTC
On 1.900.13:

```
type = 0xff41 (UNKNOWN); len = 20;02 40 40 00 00 00 00 ee ff 00 00 00 00 24 00 00 00 00 imginfo: /tmp/portage/media-libs/jasper-1.900.13/work/jasper-1.900.13/src/libjasper/jpc/jpc_t2cod.c:297: int jpc_pi_nextrpcl(jpc_pi_t *): Assertion `pi->prcno < pi->pirlvl->numprcs' failed.
```

Testcase: https://github.com/asarubbo/poc/blob/master/00013-jasper-assert-jpc_pi_nextrpcl

**Comment by mdadams** [comment] 2016-10-28 03:24
This appears to be a duplicate of the problem fixed by commit f7038068550fba0e41e1d0c355787f1dcd5bf330.  So, this test case works now.

**Closed by mdadams** 2016-10-28 03:24 UTC
