### ISSUE TITLE
segfault / null pointer access with malformed mif

### ISSUE THREAD

**Issue by hannob** [mdadams/jasper#44] opened 2016-10-21 21:37 UTC
imginfo crashes by a simple MIF file only containing the two lines MIF and end.
Test:
```
echo -e "MIF\nend"|imginfo
```

[jasper-segfault-nullpointer.zip](https://github.com/mdadams/jasper/files/545285/jasper-segfault-nullpointer.zip)

**Comment by mdadams** [comment] 2016-10-22 22:13
Already fixed on the master branch.  I think that this was a duplicate of another bug report (possibly from you).

**Closed by mdadams** 2016-10-22 22:13 UTC
